name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests using pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
          
      - name: Super-linter
        uses: super-linter/super-linter@v7.3.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Step 5: Lint the code using pylint
      - name: Run pylint
        run: |
          pylint add.py test_add.py

      # Step 6: Code quality check with SonarQube (SonarCloud)
      - name: SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: your-sonar-project-key
          organization: your-sonar-organization
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

