name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
        continue-on-error: true

      - name: SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: your-sonar-project-key
          organization: your-sonar-organization
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload to JFrog Artifactory
        run: |
          curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }} -T dist/*.tar.gz "https://your-jfrog-instance/artifactory/python-repo/"
